<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -FuC:/lazarus/packager/units/$(CPU_TARGET)-$(OS_TARGET);C:/lazarus/components/lazutils/lib/$(CPU_TARGET)-$(OS_TARGET);C:/lazarus/components/freetype/lib/$(CPU_TARGET)-$(OS_TARGET);C:/lazarus/lcl/units/$(CPU_TARGET)-$(OS_TARGET);C:/lazarus/lcl/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);C:/lazarus/components/lazcontrols/lib/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);.  -MObjFPC -Scghi -O1 -g -gl -l -vewnhibq -dLCL -dLCL$(LCL_PLATFORM) -dLAZ wredosoft.pas"/>
</CONFIG>
